# Logistic Regression from Scratch

## Imports

In [1]:
import math
import random
import numpy as np
import pandas as pd
from collections import Counter
from typing import List, Tuple, TypeVar
import tqdm

Type definitions:

In [2]:
Vector = np.ndarray

**Model:**
$$
log(\frac{Prob(classification)}{1-Prob(classification)}) = y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \dots + \beta_k x_{ik} + \epsilon
\\
probability(classification) = \frac{e^{y_i}}{1+e^{y_i}}
$$

## General Assumptions

- Features (independent variable) are linearly independent and it has a linear relationship with the dependent variable

- Features are all uncorrelated with epslon (error of model)

- For the sake of implementition, we assume the value of epsilon is zero on average (hence ignoring its effects)


**Implemented Model**

```python
y_i = beta_0 + beta_1 * x_i_1 + beta_2 * x_i_2 + ..........+ beta_k * x_i_k + epsilon

Beta = [b_0, b_1, b_2, ....... b_k]

X_i = [x_i_1, x_i_2, ........ x_i_k]

Y_i = Beta * X_i + beta_0 + epsilon   # dot product of Beta_vector and x_i
```

![alt text](https://datatab.net/assets/tutorial/Logistic-function.png)

## Implementaion

In [3]:
# LOGISTIC FUNCTION: Modified to fix floating point overflow

def logistic(x: float) -> float:
    """Applying logistic function on x"""
    if x < -709:
        return 0.0
    elif x > 709:
        return 1.0
    return 1.0 / (1 + np.exp(-x))

In [4]:
def _negative_log_likelihood(x: Vector, y: float, beta: Vector) -> float:
    """calculates the negative log likelihood for one data point"""
    if y == 1:
        return -np.log(logistic(x.dot(beta)))
    else:
        return -np.log(1 - logistic(x.dot(beta)))


# assuming different observations (data points) are independent from each other
# overoll log likelihood is the sum of individual log likelihoods.

In [5]:
def negative_log_likelihood(xs: List[Vector], ys: Vector, beta: Vector) -> float:
    return np.array([_negative_log_likelihood(x, y, beta) for x, y in zip(xs, ys)]).sum()

In [6]:
# now we have to find the gradient
def _negative_log_partial_j(x: Vector, y: float, beta: Vector, j: int) -> float:
    """calculates the j-th partial derivative at one data point,here j is the index of parameters in a single data point"""
    return -(y - logistic(x.dot(beta))) * x[j]

In [7]:
def _negative_log_gradient(x: Vector, y: float, beta: Vector) -> Vector:
    """gradient for one data point"""
    return np.array([_negative_log_partial_j(x, y, beta, j) for j in range(len(beta))])

In [8]:
def negative_log_gradient(xs: List[Vector], ys: Vector, beta: Vector) -> Vector:
    return np.array([_negative_log_gradient(x, y, beta) for x, y in zip(xs, ys)]).sum(axis=0)

## Rescaling

### pre-reqs

In [9]:
def squared_error(xs_error: Vector) -> Vector:
    """Returns the squared value of each element in the list of error"""
    return np.array([x_i**2 for x_i in xs_error])

In [10]:
def error_from_mean(xs: Vector) -> Vector:
    x_bar = xs.mean()
    return np.array([x - x_bar for x in xs])

In [11]:
def variance(xs: Vector) -> float:
    """accepts a list of data points and returns its variance from mean"""
    n = len(xs)
    xs_error = error_from_mean(xs)
    xs_error_squared = squared_error(xs_error)
    return sum(xs_error_squared) / (n - 1)

In [12]:
def std_deviation(xs: Vector) -> float:
    """accepts a list and returns its Standerd deviation from mean"""
    return math.sqrt(variance(xs))

### function def

In [13]:
def calculate_scale_parameters(data: List[Vector]) -> Tuple[Vector, Vector]:
    """returns the mean and std deviation of each position"""
    dim = len(data[0])
    means = np.mean(data, axis=0)
    stdevs = np.array([np.array([vector[i] for vector in data]).std() for i in range(dim)])
    return means, stdevs

In [14]:
def scale(data: List[Vector]) -> List[Vector]:
    """rescale the input data so that each position has a mean of 0 and std dev=1"""
    dim = len(data[0])
    means, stdevs = calculate_scale_parameters(data)
    rescaled = [v[:] for v in data]  # make a copy of each vector
    for v in rescaled:
        for i in range(dim):
            if stdevs[i] > 0:
                v[i] = (v[i] - means[i]) / stdevs[i]

    return rescaled

Gradient Descent

In [15]:
def descent_one_step(v: Vector, gradient: Vector, learning_rate: float) -> Vector:
    """Starts from v and moves a step units in oppsite direction of gradient"""
    assert len(v) == len(gradient), "The vector and its gradient are of different lengths"
 
    step = (-learning_rate) * gradient
    return v + step

## Train-Test split

In [16]:
# generic type to represnt a data point
X = TypeVar("X")
Y = TypeVar("Y")


def split_data(data: List[X], prob: float, seed:int|None = None) -> Tuple[List[X], List[X]]:
    """Split the given data into fractions of prob('prob' is fraction of training data set) given [[prob, 1-prob]]"""
    data = data.copy()
    random.seed(seed)
    random.shuffle(data)
    cut = int(len(data) * prob)
    return data[:cut], data[cut:]


def train_test_split(
    xs: List[X], ys: List[Y], test_pct: float, seed:int|None=None
) -> Tuple[List[X], List[X], List[Y], List[Y]]:
    """Split them by using indeices"""

    idxs = [i for i in range(len(xs))]
    train_idxs, test_idxs = split_data(idxs, 1 - test_pct, seed=seed)

    return (
        np.array([xs[i] for i in train_idxs]),      # x train
        np.array([xs[i] for i in test_idxs]),       # x test,
        np.array([ys[i] for i in train_idxs]),      # y train, 
        np.array([ys[i] for i in test_idxs]),       # y test
    )

## Fitting model into data: (*logistic regression*)

In [18]:
def fit(x_train: List[X], y_train:List[Y], learning_rate:float = 0.001, max_iter:int = 5000):
    """Returns the Beta for with the log-likelihood is maximum. Using gradient descent to minimize the negative of maximum log likelihood function"""
    
    # Pick a random starting point
    beta = np.array([random.random() for _ in range(len(x_train[0]))])

    with tqdm.trange(max_iter) as t:
        for epoch in t:
            gradient = negative_log_gradient(x_train, y_train, beta)
            beta = descent_one_step(beta, gradient, learning_rate)
            loss = negative_log_likelihood(x_train, y_train, beta)
            t.set_description(f"loss = {loss:.5f}")

    return beta

# Testing with a dataset

In [20]:
df = pd.read_csv("data/Social_Network_Ads.csv")

In [21]:
df['is_male'] = df['Gender'].map({'Male': 1, 'Female': 0})
df

User ID  Gender  Age  EstimatedSalary  Purchased  is_male
0    15624510    Male   19            19000          0        1
1    15810944    Male   35            20000          0        1
2    15668575  Female   26            43000          0        0
3    15603246  Female   27            57000          0        0
4    15804002    Male   19            76000          0        1
..        ...     ...  ...              ...        ...      ...
395  15691863  Female   46            41000          1        0
396  15706071    Male   51            23000          1        1
397  15654296  Female   50            20000          1        0
398  15755018    Male   36            33000          0        1
399  15594041  Female   49            36000          1        0

[400 rows x 6 columns]

In [22]:
features = df[["Age", "EstimatedSalary", "is_male"]]
target = df[["Purchased"]]

In [23]:
features

Age  EstimatedSalary  is_male
0     19            19000        1
1     35            20000        1
2     26            43000        0
3     27            57000        0
4     19            76000        1
..   ...              ...      ...
395   46            41000        0
396   51            23000        1
397   50            20000        0
398   36            33000        1
399   49            36000        0

[400 rows x 3 columns]

In [24]:
target

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

## Training

In [25]:
# Fitting the Logistic Regression model

xs = features.values
rescaled_xs = scale(xs)
ys = target['Purchased'].values

x_train, x_test, y_train, y_test = train_test_split(rescaled_xs, ys, 0.33, seed=0)

beta = fit(x_train=x_train, y_train=y_train, learning_rate = 0.001, max_iter = 5000)
beta

loss = 134.29922: 100%|██████████| 5000/5000 [00:31<00:00, 160.06it/s]


array([ 2.13206465,  0.66228359, -0.91532749])

## Testing

### Testing on training data

In [26]:
beta_vector = (np.array(beta)).reshape(-1, 1)
beta_vector

array([[ 2.13206465],
       [ 0.66228359],
       [-0.91532749]])

In [27]:
X = np.array(x_train)
X[:10]

array([[-1, -1,  0],
       [ 0, -1,  1],
       [-1,  0,  0],
       [-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  1,  1],
       [ 0,  0,  1],
       [ 1,  0,  0]])

In [28]:
log_scale_Y = (X @ beta_vector).squeeze()
log_scale_Y[:10]

array([-2.79434824, -1.57761108, -2.13206465, -3.04739214, -3.04739214,
       -2.13206465, -0.66228359, -0.2530439 , -0.91532749,  2.13206465])

In [29]:
# Applying Logistic function on to the log of odds scale to get the probabilty (prediction)
Y = np.vectorize(logistic)(log_scale_Y)
Y[:10]

array([0.05763035, 0.17113408, 0.10601915, 0.0453302 , 0.0453302 ,
       0.10601915, 0.34022682, 0.43707443, 0.28591091, 0.89398085])

Categorizing(labelling) results with probs >= 0.5 as '1' *(Using threshold as 0.5)*

In [30]:
predicted_purchased = Y >= 0.5

In [31]:
correctly_predicted = predicted_purchased == y_train
correctly_predicted[:10]

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True])

In [32]:
accuracy = correctly_predicted.sum() / len(correctly_predicted)
accuracy

np.float64(0.6753731343283582)

## Goodness of fit

In [34]:
def create_confusion_mat_class_report(xs, actual, threshold=0.5):

    true_positives = false_positives = true_negatives = false_negatives = 0

    for x_i, y_i in zip(xs, actual):
        prediction = logistic(np.dot(beta_vector.squeeze(), x_i))

        if y_i == 1 and prediction >= threshold:
            true_positives += 1
        elif y_i == 1:
            false_negatives += 1
        elif prediction >= threshold:
            false_positives += 1
        else:
            true_negatives += 1

    cm_mat = pd.DataFrame(
        {
            "0": [true_negatives, false_negatives],
            "1": [false_positives, true_positives],
        },
        index=[0, 1],
    )

    accuracy = (true_positives + true_negatives) / (
        true_positives + false_positives + true_negatives + false_negatives
    )
    precision = true_positives / (true_positives + false_positives)
    recall = true_positives / (true_positives + false_negatives)
    f1_score = 2 * precision * recall / (precision + recall)

    class_report = pd.DataFrame(
        {"Metric": [accuracy, precision, recall, f1_score]},
        index=["Accuracy", "Precision", "Recall", "F1-Score"],
    )

    return cm_mat, class_report

In [36]:
# Assuming threshold to be probability >= 0.5 = True
cm_mat, class_report = create_confusion_mat_class_report(x_train, y_train, threshold=0.5)

In [37]:
cm_mat

0   1
0  120  58
1   29  61

In [38]:
class_report

Metric
Accuracy   0.675373
Precision  0.512605
Recall     0.677778
F1-Score   0.583732